name: DataTracks and JavaTracks Tests

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-rust-and-java-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Current Repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Checkout Rust Application Repository
        uses: actions/checkout@v4
        with:
          repository: 'data-tracks/DataTracks'
          path: 'app'

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Run DataTracks
        run: |
          cd app
          cargo run --package data_tracks --bin data_tracks & 

      - name: Probe Status Until Connected
        env:
          TARGET_URL: http://localhost:2666/status # <-- IMPORTANT: Change this to your actual URL
          MAX_RETRIES: 60                   # Max number of attempts
          RETRY_INTERVAL_SECONDS: 5         # Time to wait between attempts
          EXPECTED_HTTP_CODE_PREFIX: 2      # Expecting 2xx status codes (200, 201, etc.)
        run: |
          for i in $(seq 1 "${MAX_RETRIES}"); do
          curl --fail "${TARGET_URL}" && break
          echo "Waiting for datatracks... $i"
          sleep "${RETRY_INTERVAL_SECONDS}"
          done 

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run Tests
        run: |
          chmod +x ./gradlew
          ./gradlew test